# Generated by Django 3.2.7 on 2021-10-29 20:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)])),
                ('wallet', models.IntegerField(default=0)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estate.area')),
                ('car_dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(default='A101', max_length=5, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('distance_to_sea', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True)),
                ('type', models.CharField(choices=[('S', 'FOR SALE'), ('R', 'FOR RENT')], max_length=50)),
                ('price', models.IntegerField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('img', models.ImageField(upload_to='')),
                ('minimum', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('capacity', models.CharField(max_length=2)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate.area')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estate.cardealer')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.like')),
                ('views', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.views')),
            ],
        ),
    ]
